spring.application.name=ChessTracker


### JPA
spring.jpa.show-sql=true
spring.datasource.url=jdbc:mysql://localhost:3306/ChessDB
spring.datasource.username=david
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
